persistence:
  enabled: true
  size: 2Gi
  storageClass: longhorn
  deleteEnabled: true
ingress:
  enabled: true
  className: nginx-internal
  hosts:
    - "docker.registry"
  annotations:
    cert-manager.io/cluster-issuer: "my-ca-issuer"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  tls:
    - hosts:
      - docker.registry
      secretName: quickstart-example-tls
  rules:
    - host: docker.registry
service:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.242
proxy:
  username: dr
  password: docker-server

