---
DNS1:
  192.168.0.1
persistentVolumeClaim:
  enabled: true
  storageClassName: longhorn
  size: 1Gi
ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - "pihole.home"
serviceWeb:
  loadBalancerIP: 192.168.0.240
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
serviceDns:
  loadBalancerIP: 192.168.0.240
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
replicaCount: 1
