repositories:
  - name: longhorn
    url: https://charts.longhorn.io
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: mojo2600
    url: https://mojo2600.github.io/pihole-kubernetes/
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: jetstack
    url: https://charts.jetstack.io
  - name: twuni
    url: https://helm.twun.io
  - name: makeplane
    url: https://helm.plane.so/
---
releases:
  - name: cert-manager-clusterissuer
    namespace: cert-manager-system
    chart: jetstack/cert-manager
    version: 1.15.3
    set:
      - name: crds.enabled
        value: true

  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    version: 1.7.1

  - name: metallb
    chart: metallb/metallb
    namespace: metallb-system
    version: 0.14.5

  - name: pihole
    namespace: pihole-system
    chart: mojo2600/pihole
    version: 2.26.1
    values:
      - ./values/pihole.values.yaml

  - name: ingress-nginx-internal
    namespace: nginx-system
    chart: ingress-nginx/ingress-nginx
    version: 4.11.2
    values:
      - ./values/nginx-internal.values.yaml

  - name: externaldns-pihole
    namespace: pihole-system
    chart: bitnami/external-dns
    version: 8.0.1
    values:
      - ./values/externaldns.values.yaml

  - name: docker-registry
    namespace: docker-registry-system
    chart: twuni/docker-registry
    version: 2.2.3
    values:
      - ./values/docker-registry.values.yaml

  - name: plane-app
    namespace: plane-app-system
    chart: makeplane/plane-ce
    version: 1.0.22
    values:
      - ./values/plane.values.yaml
